baseURL = 'https://example.org/'
languageCode = 'en-US'
# TODO: i18n
title = 'My New Hugo Site'
copyright = '' # set it according to your needs

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.renderer]
      # set it to true if you want to allow raw HTML in markdown, useful if you want to use static statuses template directly from api.
      # use it at your own risk.
      unsafe = true
  [markup.highlight]
    noClasses = false # to make syntax highlighting really works.

[outputs]
  home = ["HTML", "RSS", "JSON"] # add JSON for search to work

[params]
headerStyle = 'terminal' # choose between "terminal" and "386" (default is 386), or you can create one, simply put it into "assets/css/header/".
siteCoverImage = '' # path to the image you want to use as the site cover image
# the 'type' of the posts displayed in the homepage (default is posts).
# To make it simple, you should put all of your writings into 'contents/[defaultPostsType]/'.
# see https://gohugo.io/methods/page/type/#article for details.
defaultPostsType = 'posts'
[params.article]
# set it to true if you want to show comments in your posts
# To set it up correctly, you need to put some configurations in 'config.toml' and 'layouts/partials/comments.html'.
showComments = false
[params.author]
    name = "Wheatley" # from https://theportalwiki.com/wiki/Wheatley :P, change it to suit your needs.
    email = "hello@example.com" # maybe you need it.

[params.search]
  # set a search method if you want to enable search feature
  # keep in mind that JavaScript is needed for SSGs like Hugo to enable search.
  #method = "fastsearch"
  # fastsearch is set by default, it can be used anywhere in site by pressing Meta/Cmd + / .
  # searchform can also be used, by using this you should create a search page under /search with 'search' layout.


[[menus.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 20

[[menus.main]]
  name = 'Tags'
  pageRef = '/tags'
  weight = 30

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"
